### ISSUE TITLE
Consider allowing manual username/password passing to Trino client

### ISSUE THREAD

**Issue by bdnewto** [open-aviation/pyopensky#113]
I don't like having passwords in config files, and I prefer to avoid authenticating in the browser.  I propose the addition of 7 lines of code to enable "manual" passing of the password and username (while keeping all the default behavior).   When the Trino client is instantiated I propose the passing of a username and password, that can replace the need to put the passwork in the config file at the expense having to request it in the script/notebook (or store it there).   

Adding the following to class Trino in trino.py does the trick: 

 ```
def __init__(self, manual_trino_username=None, manual_trino_password=None):
        global trino_username
        global trino_password
        if manual_trino_username: #set if provided manually
            trino_username = manual_trino_username
        if manual_trino_password:
            trino_password = manual_trino_password
```

Then you can do something like:

```
from pyopensky import trino
from datetime import datetime, timedelta
from getpass import getpass

username = input("Trino username: ")
password = getpass(prompt='Trino password: ')
trino_client = trino.Trino(manual_trino_username=username, manual_trino_password=password)
df = trino_client.history(datetime.strptime("2023-03-23T02:23:00Z", "%Y-%m-%dT%H:%M:%S%z"), 
                  datetime.strptime("2023-03-23T02:24:00Z", "%Y-%m-%dT%H:%M:%S%z"), callsign="SWA1147 ")
display(df)
```

Where it propmts for the username and password in the script/notebook. 

I'm hopeful you'll consider adding this feature.

**Comment by xoolive** [comment]
Thank you for your message,

You will find in the documentation other ways of authenticating: 
https://open-aviation.github.io/pyopensky/credentials.html#fallback-configuration

I am sorry if none of them suits you, but adding credentials in the constructor of the Trino class is not an option as one of our main concern is finding leaked credentials inside code or notebook found on Github.

**Comment by bdnewto** [comment]
Undersood.   Thank you.

Ben
________________________________
From: Xavier Olive ***@***.***>
Sent: Friday, October 11, 2024 2:10 AM
To: open-aviation/pyopensky ***@***.***>
Cc: Newton, Ben ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [open-aviation/pyopensky] Consider allowing manual username/password passing to Trino client (Issue #113)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Thank you for your message,

You will find in the documentation other ways of authenticating:
https://open-aviation.github.io/pyopensky/credentials.html#fallback-configuration

I am sorry if none of them suits you, but adding credentials in the constructor of the Trino class is not an option as one of our main concern is finding leaked credentials inside code or notebook found on Github.
