### ISSUE TITLE
"raw" query using operational_status_data4 table has a weird behaviour

### ISSUE THREAD

**Issue by ElSabio97** [open-aviation/pyopensky#5]
Hi @junzis !

I continue on my quest to get RA events over europe. I have edited the `Impala_Wrapper.py` to work with operational_status_data4 table instead of the rollcall_replies_data4 table. 

You can see the two modifications I have done to the original file here :

Lines 104, 105, 106:
```
elif type == "raw":
            table = "operational_status_data4"
            time_col = "mintime"
```
Lines 160,161,162:
```
extra_filter = ""
        if table == "operational_status_data4":
            extra_filter += "AND hastcasresolutionadvisory=true AND hasoperationaltcas=1 AND subtypecode=0"
```
The query I'm doing is this one:

```
from pyopensky import OpenskyImpalaWrapper
opensky = OpenskyImpalaWrapper()

df = opensky.query(
    type="raw",
    start="2019-07-10 00:00",
    end="2019-07-11 07:20",
    bound=[33, -14, 65, 31]
)
```
As a result of this query, console gives this output:

```
* Server connection successful!
** You are query raw messages with boundary.
** An ADS-B query will be performed to get ICAO codes.
** 10004 number of ICAOs.
* Obtaining details of the query...
* OpenSky Impala: 10000 of records found.
* Fetching records...
* No record found.
```
Now, this is weird, but what is weirder is that if you change the end datetime to `end="2019-07-11 07:15"`, you will "only" get 9990 ICAO's and then the output would be:

```
* Server connection successful!
** You are query raw messages with boundary.
** An ADS-B query will be performed to get ICAO codes.
** 9990 number of ICAOs.
* Obtaining details of the query...
* OpenSky Impala: 142 of records found.
* Fetching records...
* Records downloaded.
```
All good and all. I have been playing with the end datetime to see if the limit is always 10000 and seems like that.

What am I missing?

Edit. 
If the raw query is done to get over 10000 ICAO's with an unedited `Impala_Wrapper.py` the error persists.

**Comment by xoolive** [comment]
Closing issues with new release of pyopensky, please open a new issue if still applicable with pyopensky>2.0
