### ISSUE TITLE
No ability to filter out non-aircraft ground vehicles

### ISSUE THREAD

**Issue by Golenr** [open-aviation/pyopensky#6]
The filter I want to apply (beyond time interval and bounding box) is the filter to only recognize aircraft and exclude the on ground vehicles such as cars and the like which are not aircraft. 

A first view inspection shows the ground vehicles mostly share the following criteria: squawk != NaN or len(callsign) <= 4

**Comment by xoolive** [comment]
Closing issues with new release of pyopensky, please open a new issue if still applicable with pyopensky>2.0
