### ISSUE TITLE
Unexpected behaviour trino.history start/stop params

### ISSUE THREAD

**Issue by quinten-goens** [open-aviation/pyopensky#64]
Hi!

I ran into a mismatch between requested timeframe and received timeframe using trino.history(). When I run the following code: 

```python
from pyopensky.trino import Trino
from datetime import datetime, timedelta
import pandas as pd

# Initialize Trino
trino = Trino()

# Bounding box around LSZH
bounds = (3.4981903989707055, 44.04369159096895, 13.597921601029295, 50.87242040903105)

# Timeframe
start = datetime(2024, 1, 1, 0, 0, 0)
stop =  datetime(2024, 1, 1, 1, 0, 0) 

statevectors = trino.history(start=start, stop=stop, bounds=bounds)

print(f"Minimum time: {statevectors.time.min()}")
print(f"Maximum time: {statevectors.time.max()}")
```

I get the output:
```
Minimum time: 2024-01-01 00:00:01+00:00
Maximum time: 2024-01-01 00:35:08+00:00
```
However, when I input 

```python
start = datetime(2024, 1, 1, 0, 0, 0)
stop =  datetime(2024, 1, 1, 1, 0, 1) 
```

I get the output 

```
Minimum time: 2024-01-01 00:00:01+00:00
Maximum time: 2024-01-01 01:00:01+00:00
```

Any idea what's happening? Simultaneously I get this warning

```
/home/cdsw/.local/lib/python3.9/site-packages/pyopensky/trino.py:571: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  StateVectorsData4.hour >= start_ts.floor("1H"),
/home/cdsw/.local/lib/python3.9/site-packages/pyopensky/trino.py:572: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  StateVectorsData4.hour < stop_ts.ceil("1H"),
```

In the attachment my pip freeze with my current versions (some might be outdated because I work in a 'managed' environment). 

[requirements (1).txt](https://github.com/open-aviation/pyopensky/files/14605166/requirements.1.txt) 

Thank you for any help you may provide!

**Comment by xoolive** [comment]
Hi Quinten,
I think I encountered/fixed an issue which could be related to yours.
Could you try to upgrade with the latest commit version and confirm/infirm whether the issue is still there?
If it is still here I will try to run/fix your code later.

**Comment by quinten-goens** [comment]
Hi @xoolive, 

I tried out my reprex with the latest commit 
`pyopensky @ git+https://github.com/open-aviation/pyopensky.git@19cef3debbd7cbc908d6e1880fa79f6f8631dffb`
and the issue persists. I get an identical output. 

Thanks for looking into this!

**Comment by xoolive** [comment]
![image](https://github.com/open-aviation/pyopensky/assets/1360812/e9d45051-7332-414f-b158-d018e94bcf80)

I think it looks like just what is in base at this point :man_shrugging: 
A big gap between 2024-01-01 00:35:08+00:00	and 2024-01-01 01:00:01+00:00
