### ISSUE TITLE
Can't download all raw ADS-B messages

### ISSUE THREAD

**Issue by DME-3** [open-aviation/pyopensky#82]
Dear pyopensky maintainers,

I am trying to find out if it is possible to retrieve all raw ADS-B messages from the OSN using the trino access.

Using trino.rawdata() gets by default data from the RollcallRepliesData4 table. The messages are Mode S replies with DF = 4, 5, 20 or 21. I couldn't find if there is any other table I can use to download either all raw messages, all raw ADS-B messages (i.e. only DF = 17), or only ADS-B messages of a certain TC.

I am for example interested in finding DF = 17, TC = 28 aircraft status messages. I had no luck with rawdata, neither with reading from operational_status_data4 (I get only TC = 31 messages).

Any help appreciated! Thanks

**Comment by xoolive** [comment]
You have the list of all available/supported tables here: https://github.com/open-aviation/pyopensky/blob/master/src/pyopensky/schema.py, and there is a parameter in `rawdata()` to pass the name of the table you want to query.

About your question, ADS-B messages are all split in different tables:
- TC=31/BDS=65 is Aircraft Operation Status which matches `operational_status_data4`
- TC=28/BDS=61 is Aircraft Status, which... I can't find in my list :)

@masorx is there a table where those messages are stored? (@DME-3 if there is, we will need to add the proper class in the schema.py so the `rawquery()` function works)

**Comment by DME-3** [comment]
Thanks @xoolive,

Indeed, I think it boils down to the question of whether aircraft status messages are available from OSN. Let's see!

**Comment by DME-3** [comment]
Follow-up after a quick evaluation on my side:

Trino provides access to the following tables:

| Table                     |
|---------------------------|
| flarm_raw                 |
| flights_data4             |
| flights_data5             |
| **identification_data4**      |
| **operational_status_data4**  |
| **position_data4**            |
| **rollcall_replies_data4**    |
| state_vectors_data4       |
| **velocity_data4**            |

Only the tables in **bold** contain rawmsg data.

From samples of 50k lines, I can see that these tables contain only the following DF, TC, and BDS:

| Table                     | Supported DF         | Supported TC         | Supported BDS                        |
|---------------------------|----------------------|----------------------|--------------------------------------|
| identification_data4      | 17, 18               | 2, 3, 4              | BDS08                                |
| operational_status_data4  | 17, 18               | 31                   | BDS65                                |
| position_data4            | 17                   | 7, 8, 11, 12, 18     | BDS05, BDS06                         |
| rollcall_replies_data4    | 4, 5, 20, 21         | -                    | BDS10, BDS17, BDS20, BDS30, BDS40, BDS50, BDS60 |
| velocity_data4            | 17, 18               | 19                   | BDS09                                |

So, unless I missed something it seems that the answer is that **it is not possible to retrieve raw data from any message, in particular TC: 28 messages**. If you agree I would therefore close the issue.

Note:  schema.py contains definitions for tables corresponding to `acas_data4` and `allcall_replies_data4`, which are apparently not suppported anymore. Do they have any other use?

**Comment by masorx** [comment]
Hi,

Just a note that acas_data4 and allcall_replies_data4 should come back at some point - if they have any use case, that is. We can't always tell, we're deep into the long tail of what some people -- very infreqeuently -- need and must weigh that agaisnt the added complexity.

**Comment by xoolive** [comment]
@masorx thanks for the detailed answer

`acas_data4` is definitely useful. 
`allcall_replies_data4` I am not so sure.
