### ISSUE TITLE
opensky.request has been lost

### ISSUE THREAD

**Issue by MICHELEVELLA** [open-aviation/pyopensky#88]
Before the changeover to Trino from Impala, I used the opensky.request  to make a customized SQL request. The reason was that it was the only method for me to request to download the data every 30 seconds not every second for every flight. How can I do the same command with the new system?

**Comment by xoolive** [comment]
You have the trino.query() function, that is called by other functions. You can pass text as before (although there has been some renaming/recasing in tables and features), so it is recommended to use the sqlalchemy structures instead.

Sorry, I am always confused with those synonyms (query/request), often having both in my code for different usage, and here it broke.

https://github.com/open-aviation/pyopensky/blob/7f60551a3127b4e393629d24f058b3f64b1e3410/src/pyopensky/trino.py#L134
